name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Remove electron-is-dev dependency
        run: npm uninstall electron-is-dev
      
      - name: Build Electron app
        run: npm run electron:build
      
      - name: List files in release directory
        run: Get-ChildItem -Path release -Recurse | Format-Table Name, Length
      
      # Nuevos pasos para Microsoft Store
      - name: Install electron-windows-store
        run: |
          npm install -g electron-windows-store@2.1.0
          npm list -g electron-windows-store

      - name: Create Windows Store Package
        run: |
          npx electron-windows-store --input-directory release --output-directory windows-store-package --package-version ${{ github.ref_name }} --package-name CupControl --package-display-name "Cup Control" --publisher-display-name "Moises Magna" --identity-name "MoisesMagna.CupControl" --flatten
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: |
            release/*.exe
            release/*.zip
            windows-store-package/*.msix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}